language: node_js
node_js:
  - '10'
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn lint
  - yarn test:coverage --runInBand --no-cache
  - yarn test --runInBand --no-cache
  - codecov
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
